/**
* This script avoids the creation of same audio tags in different files
* All tags will be created here and no ones will be created in html files
**/


let AUDIO = {
	brought: 'https://dictionary.cambridge.org/media/english/us_pron/b/bro/broug/brought.mp3',
	bought: 'https://dictionary.cambridge.org/media/english/us_pron/b/bou/bough/bought.mp3',
	caught: 'https://dictionary.cambridge.org/media/english/us_pron/c/cau/caugh/caught.mp3',
	fought: 'https://dictionary.cambridge.org/media/english/us_pron/u/usl/usl30/usl30138.mp3',
	sought: 'https://dictionary.cambridge.org/media/english/us_pron/s/sou/sough/sought.mp3',
	taught: 'https://dictionary.cambridge.org/media/english/us_pron/t/tau/taugh/taught.mp3',
	thought: 'https://dictionary.cambridge.org/media/english/us_pron/t/tho/thoug/thought.mp3',
	beat: 'https://dictionary.cambridge.org/media/english/us_pron/b/bea/beat_/beat.mp3',
	bet: 'https://dictionary.cambridge.org/media/english/us_pron/b/bet/bet__/bet.mp3',
	bid: 'https://dictionary.cambridge.org/media/english/us_pron/b/bid/bid__/bid.mp3',
	cast: 'https://dictionary.cambridge.org/media/english/us_pron/c/cas/cast_/cast.mp3',
	cost: 'https://dictionary.cambridge.org/media/english/us_pron/c/cos/cost_/cost.mp3',
	cut: 'https://dictionary.cambridge.org/media/english/us_pron/c/cut/cut__/cut.mp3',
	hit: 'https://dictionary.cambridge.org/media/english/us_pron/h/hit/hit__/hit.mp3',
	hurt: 'https://dictionary.cambridge.org/media/english/us_pron/h/hur/hurt_/hurt.mp3',
	let: 'https://dictionary.cambridge.org/media/english/us_pron/l/let/let__/let.mp3',
	put: 'https://dictionary.cambridge.org/media/english/us_pron/p/put/put__/put.mp3',
	quit: 'https://dictionary.cambridge.org/media/english/us_pron/q/qui/quit_/quit.mp3',
	read: 'https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscld/uscld02041.mp3',
	set: 'https://dictionary.cambridge.org/media/english/us_pron/s/set/set__/set.mp3',
	shed: 'https://dictionary.cambridge.org/media/english/us_pron/s/she/shed_/shed.mp3',
	shut: 'https://dictionary.cambridge.org/media/english/us_pron/s/shu/shut_/shut.mp3',
	spit: 'https://dictionary.cambridge.org/media/english/us_pron/s/spi/spit_/spit.mp3',
	spread: 'https://dictionary.cambridge.org/media/english/us_pron/s/spr/sprea/spread.mp3',
	bred: 'https://dictionary.cambridge.org/media/english/us_pron/c/cdo/cdo03/cdo0318usbred0654.mp3',
	chose: 'https://dictionary.cambridge.org/media/english/us_pron/c/cho/chose/chose.mp3',
	fed: 'https://dictionary.cambridge.org/media/english/us_pron/f/fed/fed__/fed.mp3',
	met: 'https://dictionary.cambridge.org/media/english/us_pron/m/met/met__/met.mp3',
	shot: 'https://dictionary.cambridge.org/media/english/us_pron/s/sho/shot_/shot_shoot.mp3',
	crept: 'https://dictionary.cambridge.org/media/english/us_pron/c/cre/crept/crept.mp3',
	kept: 'https://dictionary.cambridge.org/media/english/us_pron/k/kep/kept_/kept_keep.mp3',
	slept: 'https://dictionary.cambridge.org/media/english/us_pron/s/sle/slept/slept.mp3',
	swept: 'https://dictionary.cambridge.org/media/english/us_pron/s/swe/swept/swept.mp3',
	paid: 'https://dictionary.cambridge.org/media/english/us_pron/p/pai/paid_/paid.mp3',
	said: 'https://dictionary.cambridge.org/media/english/us_pron/s/sai/said_/said.mp3',
	laid: 'https://dictionary.cambridge.org/media/english/us_pron/l/lai/laid_/laid.mp3',
	bore: 'https://dictionary.cambridge.org/media/english/us_pron/c/cal/cald4/cald4us0269.mp3',
	swore: 'https://dictionary.cambridge.org/media/english/us_pron/s/swo/swore/swore.mp3',
	wore: 'https://dictionary.cambridge.org/media/english/us_pron/w/wor/wore_/wore.mp3',
	tore: 'https://dictionary.cambridge.org/media/english/us_pron/t/tor/tore_/tore.mp3',
	awoke: 'https://dictionary.cambridge.org/media/english/us_pron/a/awo/awoke/awoke.mp3',
	arose: 'https://dictionary.cambridge.org/media/english/us_pron/a/aro/arose/arose.mp3',
	became: 'https://dictionary.cambridge.org/media/english/us_pron/b/bec/becam/became_become.mp3',
	beheld: 'https://dictionary.cambridge.org/media/english/us_pron/b/beh/behel/beheld_behold.mp3',
	began: 'https://dictionary.cambridge.org/media/english/us_pron/b/beg/began/began_begin.mp3',
	broke: 'https://dictionary.cambridge.org/media/english/us_pron/b/bro/broke/broke.mp3',
	built: 'https://dictionary.cambridge.org/media/english/us_pron/b/bui/built/built.mp3',
	blew: 'https://dictionary.cambridge.org/media/english/us_pron/b/ble/blew_/blew.mp3',
	clung: 'https://dictionary.cambridge.org/media/english/us_pron/c/clu/clung/clung.mp3',
	came: 'https://dictionary.cambridge.org/media/english/us_pron/c/cam/came_/came.mp3',
	dug: 'https://dictionary.cambridge.org/media/english/us_pron/d/dug/dug__/dug.mp3',
	did: 'https://dictionary.cambridge.org/media/english/us_pron/d/did/did__/did.mp3',
	drew: 'https://dictionary.cambridge.org/media/english/us_pron/d/dre/drew_/drew.mp3',
	drank: 'https://dictionary.cambridge.org/media/english/us_pron/d/dra/drank/drank.mp3',
	drove: 'https://dictionary.cambridge.org/media/english/us_pron/d/dro/drove/drove.mp3',
	ate: 'https://dictionary.cambridge.org/media/english/us_pron/a/ate/ate__/ate.mp3',
	fell: 'https://dictionary.cambridge.org/media/english/us_pron/f/fel/fell_/fell.mp3',
	felt: 'https://dictionary.cambridge.org/media/english/us_pron/f/fel/felt_/felt.mp3',
	found: 'https://dictionary.cambridge.org/media/english/us_pron/f/fou/found/found.mp3',
	fled: 'https://dictionary.cambridge.org/media/english/us_pron/f/fle/fled_/fled.mp3',
	flung: 'https://dictionary.cambridge.org/media/english/us_pron/f/flu/flung/flung.mp3',
	forgot: 'https://dictionary.cambridge.org/media/english/us_pron/f/for/forgo/forgot_forget.mp3',
	forgave: 'https://dictionary.cambridge.org/media/english/us_pron/f/for/forga/forgave.mp3',
	got: 'https://dictionary.cambridge.org/media/english/us_pron/g/got/got__/got.mp3',
	gave: 'https://dictionary.cambridge.org/media/english/us_pron/g/gav/gave_/gave.mp3',
	grew: 'https://dictionary.cambridge.org/media/english/us_pron/g/gre/grew_/grew.mp3',
	held: 'https://dictionary.cambridge.org/media/english/us_pron/h/hel/held_/held.mp3',
	knew: 'https://dictionary.cambridge.org/media/english/us_pron/k/kne/knew_/knew.mp3',
	lent: 'https://dictionary.cambridge.org/media/english/us_pron/l/len/lent_/lent.mp3',
	made: 'https://dictionary.cambridge.org/media/english/us_pron/m/mad/made_/made.mp3',
	rode: 'https://dictionary.cambridge.org/media/english/us_pron/r/roa/road_/road.mp3',
	rang: 'https://dictionary.cambridge.org/media/english/us_pron/r/ran/rang_/rang.mp3',
	rose: 'https://dictionary.cambridge.org/media/english/us_pron/r/ros/rose_/rose.mp3',
	ran: 'https://dictionary.cambridge.org/media/english/us_pron/r/ran/ran__/ran.mp3',
	sent: 'https://dictionary.cambridge.org/media/english/us_pron/c/cen/cent_/cent.mp3',
	shone: 'https://dictionary.cambridge.org/media/english/us_pron/s/sho/shone/shone.mp3',
	shrank: 'https://dictionary.cambridge.org/media/english/us_pron/s/shr/shran/shrank.mp3',
	sang: 'https://dictionary.cambridge.org/media/english/us_pron/s/san/sang_/sang.mp3',
	sank: 'https://dictionary.cambridge.org/media/english/us_pron/s/san/sank_/sank.mp3',
	sat: 'https://dictionary.cambridge.org/media/english/us_pron/s/sat/sat_0/sat_02_00.mp3',
	slung: 'https://dictionary.cambridge.org/media/english/us_pron/s/slu/slung/slung.mp3',
	spent: 'https://dictionary.cambridge.org/media/english/us_pron/s/spe/spent/spent.mp3',
	spun: 'https://dictionary.cambridge.org/media/english/us_pron/s/spu/spun_/spun.mp3',
	sprang: 'https://dictionary.cambridge.org/media/english/us_pron/s/spr/spran/sprang.mp3',
	stuck: 'https://dictionary.cambridge.org/media/english/us_pron/s/stu/stuck/stuck.mp3',
	stung: 'https://dictionary.cambridge.org/media/english/us_pron/s/stu/stung/stung.mp3',
	stank: 'https://dictionary.cambridge.org/media/english/us_pron/s/sta/stank/stank.mp3',
	strove: 'https://dictionary.cambridge.org/media/english/us_pron/s/str/strov/strove.mp3',
	swam: 'https://dictionary.cambridge.org/media/english/us_pron/s/swa/swam_/swam.mp3',
	swung: 'https://dictionary.cambridge.org/media/english/us_pron/s/swu/swung/swung.mp3',
	threw: 'https://dictionary.cambridge.org/media/english/us_pron/t/thr/threw/threw.mp3',
	won: 'https://dictionary.cambridge.org/media/english/us_pron/e/eus/eus75/eus75023.mp3',
	wrote: 'https://dictionary.cambridge.org/media/english/us_pron/r/rig/right/right.mp3',
	bound: 'https://dictionary.cambridge.org/media/english/us_pron/b/bou/bound/bound.mp3',
	bit: 'https://dictionary.cambridge.org/media/english/us_pron/b/bit/bit__/bit.mp3',
	bent: 'https://dictionary.cambridge.org/media/english/us_pron/b/ben/bent_/bent.mp3',
	dealt: 'https://dictionary.cambridge.org/media/english/us_pron/d/dea/dealt/dealt_deal.mp3',
	flew: 'https://dictionary.cambridge.org/media/english/us_pron/f/fle/flew_/flew.mp3',
	froze: 'https://dictionary.cambridge.org/media/english/us_pron/f/fro/froze/froze.mp3',
	went: 'https://dictionary.cambridge.org/media/english/us_pron/w/wen/went_/went.mp3',
	ground: 'https://dictionary.cambridge.org/media/english/us_pron/g/gro/groun/ground.mp3',
	had: 'https://dictionary.cambridge.org/media/english/us_pron/h/had/had__/had.mp3',
	led: 'https://dictionary.cambridge.org/media/english/us_pron/l/lea/lead_/lead_08_00.mp3',
	left: 'https://dictionary.cambridge.org/media/english/us_pron/l/lef/left_/left.mp3',
	lay: 'https://dictionary.cambridge.org/media/english/us_pron/l/lay/lay__/lay.mp3',
	lost: 'https://dictionary.cambridge.org/media/english/us_pron/l/los/lost_/lost_lose.mp3',
	meant: 'https://dictionary.cambridge.org/media/english/us_pron/m/mea/meant/meant.mp3',
	overtook: 'https://dictionary.cambridge.org/media/english/us_pron/u/usl/usl30/usl30271.mp3',
	saw: 'https://dictionary.cambridge.org/media/english/us_pron/s/saw/saw__/saw.mp3',
	sold: 'https://dictionary.cambridge.org/media/english/us_pron/s/sol/sold_/sold.mp3',
	shook: 'https://dictionary.cambridge.org/media/english/us_pron/s/sho/shook/shook.mp3',
	slew: 'https://dictionary.cambridge.org/media/english/us_pron/s/sle/slew_/slew.mp3',
	spoke: 'https://dictionary.cambridge.org/media/english/us_pron/s/spo/spoke/spoke.mp3',
	stood: 'https://dictionary.cambridge.org/media/english/us_pron/s/sto/stood/stood.mp3',
	understood: 'https://dictionary.cambridge.org/media/english/us_pron/u/und/under/understood_understand.mp3',
	stole: 'https://dictionary.cambridge.org/media/english/us_pron/s/sto/stole/stole.mp3',
	struck: 'https://dictionary.cambridge.org/media/english/us_pron/s/str/struc/struck.mp3',
	took: 'https://dictionary.cambridge.org/media/english/us_pron/t/too/took_/took.mp3',
	told: 'https://dictionary.cambridge.org/media/english/us_pron/t/tol/told_/told.mp3',
	trod: 'https://dictionary.cambridge.org/media/english/us_pron/t/tro/trod_/trod.mp3',
	underwent: 'https://dictionary.cambridge.org/media/english/us_pron/u/und/under/underwent.mp3',
	wound: 'https://dictionary.cambridge.org/media/english/us_pron/w/wou/wound/wound_02_00.mp3'
}

function create_audio(IDS) {

	for (id of IDS) {
		let audio     = document.createElement('AUDIO')
		audio.preload = 'none'
		audio.id      = id + '_audio'
		audio.type    = 'audio/mpeg'
		audio.src  = AUDIO[id]

		document.body.appendChild(audio)
	}

}
